project:
  type: website
  output-dir: docs
  resources:
    - google6c15a515e715b4c1.html

website:
  title: "Bedirhan Avdanci"
  site-url: "https://bedirhanavdanci.github.io"

  navbar:
    right:
      - text: Blog
        href: posts.qmd
      - text: Publications
        href: publications.qmd
      - text: CV
        href: CV_BedirhanAvdanci.pdf
      - text: Contact
        href: contact.qmd
    search: false
    background: transparent
    foreground: "#252525"

  page-footer:
    center: |
      © 2026 Bedirhan Avdancı

  description: "Bedirhan Avdancı — MSc student in Marine Microbiology at the Max Planck Institute for Marine Microbiology."

format:
  html:
    theme:
      - cosmo
      - custom.scss
    mainfont: Charter
    toc: false
    smooth-scroll: true
    anchor-sections: false
    code-fold: true
    code-tools: false

metadata-files:
  - _metadata.yml

execute:
  freeze: auto

editor: visual

schema:
  type: Person
  name: "Bedirhan Avdancı"
  url: "https://bedirhanavdanci.github.io"
  sameAs:
    - "https://orcid.org/0009-0000-1079-3049"
    - "https://scholar.google.com/citations?user=jAF-BsgAAAAJ&hl=tr"
    - "https://x.com/bedirhan_avd"
    - "https://www.researchgate.net/profile/Bedirhan-Avdanci?ev=hdr_xprf"